/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PhemiumPdfViewer {
        "disableScrolling": boolean;
        /**
          * Si es false, desactiva herramientas de edición (resaltado, texto, tinta, etc.), comentarios y firma en la barra del visor PDF.js.
         */
        "enableAnnotationEditing": boolean;
        "enableManualFullscreenFallback": boolean;
        "enableSearch": boolean;
        "enableSideDrawer": boolean;
        "enableToolbar": boolean;
        /**
          * Nombre de archivo sugerido para la descarga en Cordova (atributo file del host).
         */
        "file": string;
        "getPage": () => Promise<any>;
        "page": number;
        "print": () => Promise<void>;
        "scale": "auto" | "page-fit" | "page-width" | number;
        "setScale": (scale: "auto" | "page-fit" | "page-width" | number) => Promise<void>;
        "src": string;
    }
}
export interface PhemiumPdfViewerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPhemiumPdfViewerElement;
}
declare global {
    interface HTMLPhemiumPdfViewerElementEventMap {
        "pageChange": number;
        "linkClick": string;
        "fullscreenToggle": boolean;
    }
    interface HTMLPhemiumPdfViewerElement extends Components.PhemiumPdfViewer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPhemiumPdfViewerElementEventMap>(type: K, listener: (this: HTMLPhemiumPdfViewerElement, ev: PhemiumPdfViewerCustomEvent<HTMLPhemiumPdfViewerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPhemiumPdfViewerElementEventMap>(type: K, listener: (this: HTMLPhemiumPdfViewerElement, ev: PhemiumPdfViewerCustomEvent<HTMLPhemiumPdfViewerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPhemiumPdfViewerElement: {
        prototype: HTMLPhemiumPdfViewerElement;
        new (): HTMLPhemiumPdfViewerElement;
    };
    interface HTMLElementTagNameMap {
        "phemium-pdf-viewer": HTMLPhemiumPdfViewerElement;
    }
}
declare namespace LocalJSX {
    interface PhemiumPdfViewer {
        "disableScrolling"?: boolean;
        /**
          * Si es false, desactiva herramientas de edición (resaltado, texto, tinta, etc.), comentarios y firma en la barra del visor PDF.js.
         */
        "enableAnnotationEditing"?: boolean;
        "enableManualFullscreenFallback"?: boolean;
        "enableSearch"?: boolean;
        "enableSideDrawer"?: boolean;
        "enableToolbar"?: boolean;
        /**
          * Nombre de archivo sugerido para la descarga en Cordova (atributo file del host).
         */
        "file"?: string;
        "onFullscreenToggle"?: (event: PhemiumPdfViewerCustomEvent<boolean>) => void;
        "onLinkClick"?: (event: PhemiumPdfViewerCustomEvent<string>) => void;
        "onPageChange"?: (event: PhemiumPdfViewerCustomEvent<number>) => void;
        "page"?: number;
        "scale"?: "auto" | "page-fit" | "page-width" | number;
        "src"?: string;
    }
    interface IntrinsicElements {
        "phemium-pdf-viewer": PhemiumPdfViewer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "phemium-pdf-viewer": LocalJSX.PhemiumPdfViewer & JSXBase.HTMLAttributes<HTMLPhemiumPdfViewerElement>;
        }
    }
}
